import Head from 'next/head'
import Footer from '../components/Footer'
import Herosection from '../components/Herosection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive footer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Herosection />
      <Footer />
    </div>
  )
}
